spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/demo?useSSL=false&statementInterceptors=com.github.kristofa.brave.mysql.MySQLStatementInterceptor&zipkinServiceName=mysql
    username: root
    password: root
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

zipkin:
  endpoint: http://localhost:9411/api/v1/spans
  service: hello

server:
  port: 8080